name: 'Arma 3 mission packing'
description: 'Binarize mission SQM, and pack as pbo using armake2'
inputs:

  mission:
    description: 'Path to the mission directory containing a mission.sqm'
    required: true

  briefingName:
    description: 'A briefing name to set in the mission sqm'
    required: false    

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mission }}
    - ${{ inputs.briefingName }}